import Head from 'next/head';
import axios from 'axios';

import styles from '@/styles/Home.module.scss';

interface IProps {
  id: string;
  name: string;
  description: string;
  url: string;
}
export default function Home({ data }: any) {
  return (
    <>
      <Head>
        <title>heegeun`s portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>
          <h1>Portfolio List</h1>
        </div>
        <div className={styles.content}>
          <div className={styles.content_filter}>
            <p>최신순</p>
          </div>
          <ul className={styles.content_list}>
            {data.map((item: IProps) => (
              <li key={item.id}>
                <span>{item.name}</span>
                <span>{item.description}</span>
                <span>{item.url}</span>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/portfolio`);
  const data = res.data;

  return {
    props: {
      data,
    },
  };
}
