import Head from 'next/head';
import axios from 'axios';

import styles from '@/styles/Home.module.scss';

interface IProps {
  id: string;
  name: string;
  description: string;
  url: string;
  note?: string;
}
export default function Home() {
  return (
    <>
      <Head>
        <title>heegeun`s portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>
          <h1>참여 프로젝트 목록</h1>
          <p>
            * 최근 작업순서에 따라 정렬되어 있으며, 최소 50%이상 기여한
            프로젝트만 기재했습니다.
            <br />* 시간이 지남에 따라 작업한 내용에서 변화가 있을 수 있습니다.
            (최대한 제외 하고 있습니다)
          </p>
          <div className={styles.title_links}>
            <a
              href="https://github.com/gusto-dev"
              target="_blank"
              className={styles.github}
            ></a>
          </div>
        </div>
        <div className={styles.content}>
          <table className={styles.content_table}>
            <colgroup>
              <col width="*" />
              <col width="120px" />
              <col width="120px" />
              <col width="120px" />
            </colgroup>
            <thead>
              <tr>
                <th>프로젝트명</th>
                <th>종류</th>
                <th>URL</th>
                <th>비고</th>
              </tr>
            </thead>
            <tbody>
              {/* {newData.map((item: IProps) => (
                <tr key={item.id}>
                  <td>{item.name}</td>
                  <td>{item.description}</td>
                  <td>
                    {item.url === '' ? (
                      <span>내부 프로젝트</span>
                    ) : (
                      <a href={item.url} target="_blank">
                        링크
                      </a>
                    )}
                  </td>
                  <td>{item.note}</td>
                </tr>
              ))} */}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
}

// export async function getStaticProps() {
//   const res = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/portfolio`);
//   const data = res.data;

//   return {
//     props: {
//       data,
//     },
//   };
// }
